nodeLinker: node-modules
npmMinimalAgeGate: 14d
npmPreapprovedPackages:
  - '@iress-oss/ids-components'
  - '@iress-oss/ids-storybook-config'
  - '@iress-oss/ids-storybook-okta'
  - '@iress-oss/ids-storybook-sandbox'
  - '@iress-oss/ids-storybook-toggle-stories'
  - '@iress-oss/ids-storybook-version-badge'
  - '@iress-oss/ids-tokens'
