import { Link } from '@tanstack/react-router';
import type { SideNavItem } from '@iress-oss/ids-components';

export const NAV_ITEMS: SideNavItem[] = [
  {
    key: 'get-started',
    icon: 'rocket_launch',
    label: 'Get Started',
    href: '/get-started/develop',
    element: Link,
    children: [
      { key: 'design', label: 'Design', href: '/get-started/design', element: Link },
      { key: 'develop', label: 'Develop', href: '/get-started/develop', element: Link,
        children: [
          { key: 'install', label: 'Install', href: '/get-started/develop', element: Link },
          { key: 'content-security-policy', label: 'Content Security Policy', href: '/get-started/content-security-policy', element: Link },
        ]
       },
    ],
  },
  {
    key: 'foundations',
    icon: 'foundation',
    label: 'Foundations',
    href: '/foundations/principles',
    element: Link,
    children: [
      { key: 'principles', label: 'Principles', href: '/foundations/principles', element: Link },
      { key: 'accessibility', label: 'Accessibility', href: '/foundations/accessibility', element: Link },
      { key: 'common-mistakes', label: 'Common Mistakes', href: '/foundations/common-mistakes', element: Link },
      { key: 'content', label: 'Content', href: '/foundations/content', element: Link },
      { key: 'iconography', label: 'Iconography', href: '/foundations/iconography', element: Link },
      { key: 'responsive-layout', label: 'Responsive Layout', href: '/foundations/responsive-layout', element: Link },
      { key: 'user-experience', label: 'User Experience', href: '/foundations/user-experience', element: Link },
      { key: 'using-components-consistently', label: 'Using Components Consistently', href: '/foundations/using-components-consistently', element: Link },
      { key: 'visual-design-standards', label: 'Visual Design Standards', href: '/foundations/visual-design-standards', element: Link },
      { key: 'z-index-stacking', label: 'Z-Index (stacking)', href: '/foundations/z-index-stacking', element: Link },
    ],
  },
  {
    key: 'components',
    icon: 'widgets',
    label: 'Components',
    href: '/components/button',
    element: Link,
    children: [
      { key: 'alert', label: 'Alert', href: '/components/alert', element: Link },
      { key: 'autocomplete', label: 'Autocomplete', href: '/components/autocomplete', element: Link },
      { key: 'button', label: 'Button', href: '/components/button', element: Link },
      { key: 'button-group', label: 'Button Group', href: '/components/button-group', element: Link },
      { key: 'checkbox', label: 'Checkbox', href: '/components/checkbox', element: Link },
      { key: 'checkbox-group', label: 'Checkbox Group', href: '/components/checkbox-group', element: Link },
      { key: 'col', label: 'Col', href: '/components/col', element: Link },
      { key: 'container', label: 'Container', href: '/components/container', element: Link },
      { key: 'divider', label: 'Divider', href: '/components/divider', element: Link },
      { key: 'expander', label: 'Expander', href: '/components/expander', element: Link },
      { key: 'field', label: 'Field', href: '/components/field', element: Link },
      { key: 'field-group', label: 'Field Group', href: '/components/field-group', element: Link },
      { key: 'icon', label: 'Icon', href: '/components/icon', element: Link },
      { key: 'image', label: 'Image', href: '/components/image', element: Link },
      { key: 'inline', label: 'Inline', href: '/components/inline', element: Link },
      { key: 'input', label: 'Input', href: '/components/input', element: Link },
      { key: 'input-currency', label: 'Input Currency', href: '/components/input-currency', element: Link },
      { key: 'label', label: 'Label', href: '/components/label', element: Link },
      { key: 'link', label: 'Link', href: '/components/link', element: Link },
      { key: 'menu', label: 'Menu', href: '/components/menu', element: Link },
      { key: 'modal', label: 'Modal', href: '/components/modal', element: Link },
      { key: 'panel', label: 'Panel', href: '/components/panel', element: Link },
      { key: 'pill', label: 'Pill', href: '/components/pill', element: Link },
      { key: 'placeholder', label: 'Placeholder', href: '/components/placeholder', element: Link },
      { key: 'popover', label: 'Popover', href: '/components/popover', element: Link },
      { key: 'progress', label: 'Progress', href: '/components/progress', element: Link },
      { key: 'provider', label: 'Provider', href: '/components/provider', element: Link },
      { key: 'radio', label: 'Radio', href: '/components/radio', element: Link },
      { key: 'radio-group', label: 'Radio Group', href: '/components/radio-group', element: Link },
      { key: 'readonly', label: 'Readonly', href: '/components/readonly', element: Link },
      { key: 'row', label: 'Row', href: '/components/row', element: Link },
      { key: 'select', label: 'Select', href: '/components/select', element: Link },
      { key: 'skeleton', label: 'Skeleton', href: '/components/skeleton', element: Link },
      { key: 'skip-link', label: 'Skip Link', href: '/components/skip-link', element: Link },
      { key: 'slideout', label: 'Slideout', href: '/components/slideout', element: Link },
      { key: 'slider', label: 'Slider', href: '/components/slider', element: Link },
      { key: 'spinner', label: 'Spinner', href: '/components/spinner', element: Link },
      { key: 'stack', label: 'Stack', href: '/components/stack', element: Link },
      { key: 'styled', label: 'Styled', href: '/components/styled', element: Link },
      { key: 'tab-set', label: 'Tab Set', href: '/components/tab-set', element: Link },
      { key: 'table', label: 'Table', href: '/components/table', element: Link },
      { key: 'tag', label: 'Tag', href: '/components/tag', element: Link },
      { key: 'tag-input', label: 'Tag Input', href: '/components/tag-input', element: Link },
      { key: 'text', label: 'Text', href: '/components/text', element: Link },
      { key: 'toaster', label: 'Toaster', href: '/components/toaster', element: Link },
      { key: 'toggle', label: 'Toggle', href: '/components/toggle', element: Link },
      { key: 'tooltip', label: 'Tooltip', href: '/components/tooltip', element: Link },
      { key: 'validation-message', label: 'Validation Message', href: '/components/validation-message', element: Link },
    ],
  },
  {
    key: 'patterns',
    icon: 'dashboard',
    label: 'Patterns',
    href: '/patterns/form',
    element: Link,
    children: [
      { key: 'breadcrumbs', label: 'Breadcrumbs', href: '/patterns/breadcrumbs', element: Link },
      { key: 'contextual-menu', label: 'Contextual Menu', href: '/patterns/contextual-menu', element: Link },
      { key: 'dropdown-menu', label: 'Dropdown Menu', href: '/patterns/dropdown-menu', element: Link },
      { key: 'feedback', label: 'Feedback', href: '/patterns/feedback', element: Link },
      { key: 'form', label: 'Form', href: '/patterns/form', element: Link },
      { key: 'search-selection', label: 'Search & Selection', href: '/patterns/search-selection', element: Link },
      { key: 'shadow', label: 'Shadow', href: '/patterns/shadow', element: Link },
      { key: 'side-nav', label: 'Side Nav', href: '/patterns/side-nav', element: Link },
    ],
  },
  {
    key: 'tokens',
    icon: 'colorize',
    label: 'Tokens',
    href: '/tokens/colour',
    element: Link,
    children: [
      { key: 'colour', label: 'Colour', href: '/tokens/colour', element: Link },
      { key: 'spacing', label: 'Spacing', href: '/tokens/spacing', element: Link },
      { key: 'radius', label: 'Radius', href: '/tokens/radius', element: Link },
      { key: 'typography', label: 'Typography', href: '/tokens/typography', element: Link },
    ],
  },
  {
    key: 'styling-props',
    icon: 'palette',
    label: 'Styling Props',
    href: '/styling-props/styling-props',
    element: Link,
    children: [
      { key: 'styling-props', label: 'Overview', href: '/styling-props/styling-props', element: Link },
      { key: 'accessibility', label: 'Accessibility', href: '/styling-props/accessibility', element: Link },
      { key: 'colour', label: 'Colour', href: '/styling-props/colour', element: Link },
      { key: 'layout', label: 'Layout', href: '/styling-props/layout', element: Link },
      { key: 'radius', label: 'Radius', href: '/styling-props/radius', element: Link },
      { key: 'sizing', label: 'Sizing', href: '/styling-props/sizing', element: Link },
      { key: 'spacing', label: 'Spacing', href: '/styling-props/spacing', element: Link },
      { key: 'typography', label: 'Typography', href: '/styling-props/typography', element: Link },
    ],
  },
  {
    key: 'resources-migration-guides',
    icon: 'update',
    label: 'Migration Guides',
    href: '/resources-migration-guides/from-v5-to-v6',
    element: Link,
    children: [
      { key: 'from-v5-to-v6', label: 'From v5 to v6', href: '/resources-migration-guides/from-v5-to-v6', element: Link },
      { key: 'from-oui-to-v6', label: 'From OUI to v6', href: '/resources-migration-guides/from-oui-to-v6', element: Link },
      { key: 'migration-from-v4-to-v5', label: 'From v4 to v5', href: '/resources-migration-guides/migration-from-v4-to-v5', element: Link },
    ],
  },
];
