/**
 * Strips CSS rules generated by the IDS preset's staticCss configuration from
 * the consumer's bundle. These classes are already shipped by IDS via
 * @iress-oss/ids-components style.css, so duplicating them in the consumer's
 * bundle only adds unnecessary weight.
 *
 * Used in createMinimalConfig() alongside cssgenDoneHook to ensure the
 * consumer's Panda output only contains CSS that is genuinely unique to their
 * application.
 *
 * Pattern coverage:
 * - Canonical spacing utility classes (gap, margin, padding, etc.) for IDS
 *   spacing tokens, including responsive breakpoint-prefixed variants and
 *   negative margin values.
 * - IDS typography composition classes (textStyle_typography.*).
 * - IDS-specific custom utility classes: focusable, span, offset, gutter,
 *   noGutter, scrollable, stretch, flexHorizontalAlign (fha),
 *   flexVerticalAlign (fva), srOnly (sr), and responsive visibility (hide_*).
 * - IDS colour and radius token classes (bg_colour.*, c_colour.*,
 *   rounded_radius.*).
 */
export function staticCssStripHook(
  artifact: string,
  content: string,
): string | void {
  if (artifact !== 'styles.css') return;

  let css = content;

  // Strip spacing utility classes for canonical IDS spacing tokens.
  //
  // Covers all Panda CSS shorthand property names for spacing with values
  // matching the IDS canonical token format `spacing.N`.
  //
  // The `\\.` in the regex matches the literal backslash+dot that Panda CSS
  // uses to escape dots in class names (e.g. .gap_spacing\.2).
  //
  // `[a-z]+` is used rather than an exhaustive explicit alternation
  // (gap|cg|rg|m|mt|...) because: (a) an exhaustive alternation triggers
  // the sonarjs/regex-complexity lint rule at this scope, and (b) the
  // `_-?spacing\\\.\d+` suffix is already sufficiently specific — only IDS
  // canonical token paths produce this pattern. Mixed-case Panda condition
  // prefixes (e.g. `progressBar\:m_spacing`) are excluded by `[a-z]+` because
  // they contain uppercase letters.
  //
  // Matches:
  //   .gap_spacing\.2{...}            canonical spacing
  //   .xs\:gap_spacing\.2{...}        responsive breakpoint-prefixed
  //   .mt_-spacing\.2{...}            negative margin
  css = css.replace(/\.(?:[a-z]+\\:)?[a-z]+_-?spacing\\\.\d+\{[^}]*\}/g, '');

  // Strip textStyle classes for IDS typography compositions.
  //
  // These may have descendant-combinator selectors (e.g. `.textStyle_X strong`)
  // so we match everything from .textStyle_typography up to the closing }.
  // This relies on Panda CSS generating flat (non-nested) CSS rules, which
  // means `[^}]+` will always stop at the correct closing brace — CSS property
  // values cannot contain unescaped `}` characters.
  //
  // Matches:
  //   .textStyle_typography\.body\.md{...}
  //   .textStyle_typography\.body\.md strong:not([class]),...{...}
  css = css.replace(/\.textStyle_typography[^}]+\}/g, '');

  // Strip IDS-specific custom utility classes.
  //
  // These use Panda's `className` option and are unique to IDS, so they are
  // safe to strip without risk of removing consumer-authored utilities.
  // The class names (focusable, fha, fva, etc.) are not standard CSS property
  // shorthands and are unlikely to be used as utility names in consumer code.
  //
  // `[^\s{]+` is safe here because `{` is in the exclusion set — it terminates
  // the match at the exact opening brace of the CSS block with no ambiguity.
  //
  // Covers: focusable, span (IressCol), offset (IressCol), gutter (IressRow),
  // noGutter (IressRow), scrollable, stretch, fha (flexHorizontalAlign),
  // fva (flexVerticalAlign).
  css = css.replace(
    /\.(focusable|span|offset|gutter|noGutter|scrollable|stretch|fha|fva)_[^\s{]+\{[^}]*\}/g,
    '',
  );

  // Strip srOnly (sr) utility classes.
  //
  // A negative lookbehind is required because the IDS preset's
  // `nestedFormLabels` condition embeds `.sr_true` inside a :not() selector
  // (e.g. `.iress-form-label:not(.sr_true)`), which would otherwise be
  // incorrectly stripped.
  css = css.replace(/(?<!\()\.sr_[^\s{]+\{[^}]*\}/g, '');

  // Strip responsive visibility utility classes (hideBelow / hideFrom).
  //
  // These utilities generate breakpoint-scoped display:none rules inside
  // @media blocks. Only the exact IDS breakpoint values are targeted.
  css = css.replace(/\.hide_(xs|sm|md|lg|xl|xxl)\{[^}]*\}/g, '');

  // Strip IDS colour token utility classes.
  //
  // Only targets classes whose value uses the IDS colour token path format
  // (`colour.*`), which is distinct from generic colour values. Safe to strip
  // because any class matching this pattern is already in IDS's style.css.
  css = css.replace(/\.bg_colour\\\.[^\s{]+\{[^}]*\}/g, '');
  css = css.replace(/\.c_colour\\\.[^\s{]+\{[^}]*\}/g, '');

  // Strip IDS radius token utility classes (borderRadius with IDS radii).
  css = css.replace(/\.rounded_radius\\\.[^\s{]+\{[^}]*\}/g, '');

  return css;
}
