import type { ReactNode } from 'react';

/**
 * Props for individual type table entries.
 * Matches the shape generated by fumadocs-typescript's remarkAutoTypeTable.
 */
interface TypeTableEntry {
  name: string;
  type: string;
  description?: string;
  default?: string;
  required?: boolean;
}

interface TypeTableProps {
  type: Record<string, TypeTableEntry>;
  children?: ReactNode;
}

/**
 * Renders a props/type table for component documentation.
 * Replaces the fumadocs-ui TypeTable component with a plain HTML table
 * styled via .docs-prose CSS and IDS design tokens.
 */
export function TypeTable({ type }: TypeTableProps) {
  const entries = Object.entries(type);

  if (entries.length === 0) return null;

  return (
    <div style={{ overflowX: 'auto', marginBottom: '1.5rem' }}>
      <table>
        <thead>
          <tr>
            <th>Prop</th>
            <th>Type</th>
            <th>Default</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          {entries.map(([name, entry]) => (
            <tr key={name}>
              <td>
                <code>{name}</code>
                {entry.required && (
                  <span
                    style={{
                      color: 'var(--ids-semantic-foreground-negative)',
                      marginLeft: '0.25rem',
                    }}
                    title="Required"
                  >
                    *
                  </span>
                )}
              </td>
              <td>
                <code style={{ fontSize: '0.8125rem' }}>{entry.type}</code>
              </td>
              <td>
                {entry.default ? (
                  <code style={{ fontSize: '0.8125rem' }}>{entry.default}</code>
                ) : (
                  <span
                    style={{ color: 'var(--ids-semantic-foreground-subtle)' }}
                  >
                    —
                  </span>
                )}
              </td>
              <td>{entry.description ?? ''}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
